- id: '1620141136807'
  alias: Security Lighting Off
  description: ''
  trigger:
  - platform: time
    at: '21:23:00'
  condition:
  - condition: state
    entity_id: person.michael
    state: not_home
  - condition: or
    conditions:
    - condition: state
      entity_id: person.susan
      state: not_home
    - condition: state
      entity_id: person.susan
      state: unknown
  action:
  - delay: 00:{{ (range(5, 15) | random) }}:00
  - service: script.security_lighting_off
    data: {}
  mode: single
- id: '1620141485436'
  alias: Security Lighting On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:25:00
  condition:
  - condition: state
    entity_id: person.michael
    state: not_home
  - condition: or
    conditions:
    - condition: state
      entity_id: person.susan
      state: not_home
    - condition: state
      entity_id: person.susan
      state: unknown
  action:
  - service: script.security_lighting_on
    data: {}
  mode: single
- id: '1630506102319'
  alias: Renew Let's Encrypt Certificate
  description: ''
  use_blueprint:
    path: mtl010957/renew_certificate_restart_nginx.yaml
    input:
      cert_expiry_sensor: sensor.cert_expiry_timestamp_ha_mtl_desert_dyndns_remote_com
      time_to_check_cert: 03:20:00
      renew_date: 20
- id: '1673967752206'
  alias: Notify Refrigerator Low Voltage
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.refrigerator_outlet_voltage
    for:
      hours: 0
      minutes: 30
      seconds: 0
    below: 110
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      title: Refrigerator Voltage Low
      message: Refrigerator Voltage has been low for over 30 minutes, check the power
        connection!
  mode: single
- id: '1681488744643'
  alias: Router LEDs Off Nighttime
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 958ab389e26ad5b402f3fa7dbf91b8ba
    entity_id: light.rt_ac68u_led
    domain: light
  mode: single
- id: '1681489013152'
  alias: 'Router LEDs On Daytime '
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 958ab389e26ad5b402f3fa7dbf91b8ba
    entity_id: light.rt_ac68u_led
    domain: light
  mode: single
- id: '1691769290763'
  alias: Reload ASUS Router Integration After Router Reboot
  description: ''
  trigger:
  - platform: time
    at: 03:40:00
  condition: []
  action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      device_id: 958ab389e26ad5b402f3fa7dbf91b8ba
  mode: single
- id: '1699751793923'
  alias: Notify When HA Started
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.notify
    data:
      message: HA Has Started
      title: 'HA Has Started '
  mode: single
