- id: '1620141136807'
  alias: Security Lighting Off
  description: ''
  trigger:
  - platform: time
    at: '21:23:00'
  condition:
  - condition: state
    entity_id: person.michael
    state: not_home
  - condition: state
    entity_id: person.susan
    state: not_home
  action:
  - delay: 00:{{ (range(5, 15) | random) }}:00
  - service: script.security_lighting_off
    data: {}
  mode: single
- id: '1620141485436'
  alias: Security Lighting On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:25:00
  condition:
  - condition: state
    entity_id: person.michael
    state: not_home
  - condition: state
    entity_id: person.susan
    state: not_home
  action:
  - service: script.security_lighting_on
    data: {}
  mode: single
- id: '1630506102319'
  alias: Renew Let's Encrypt Certificate
  description: ''
  use_blueprint:
    path: mtl010957/renew_certificate_restart_nginx.yaml
    input:
      cert_expiry_sensor: sensor.cert_expiry_timestamp_ha_mtl_desert_dyndns_remote_com
      time_to_check_cert: 03:20:00
      renew_date: 20
- id: '1673967752206'
  alias: Notify Refrigerator Low Voltage
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.refrigerator_outlet_voltage
    for:
      hours: 0
      minutes: 30
      seconds: 0
    below: 110
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      title: Refrigerator Voltage Low
      message: Refrigerator Voltage has been low for over 30 minutes, check the power
        connection!
  mode: single
