- id: '1620141136807'
  alias: Security Lighting Off
  description: ''
  trigger:
  - platform: time
    at: '21:23:00'
  condition:
  - condition: state
    entity_id: camera.living_room
    state: recording
  - condition: state
    entity_id: binary_sensor.desert_away
    state: 'on'
  action:
  - delay: 00:{{ (range(5, 15) | random) }}:00
  - service: script.security_lighting_off
  mode: single
- id: '1620141485436'
  alias: Security Lighting On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:25:00
  condition:
  - condition: state
    entity_id: camera.living_room
    state: recording
  - condition: state
    entity_id: binary_sensor.desert_away
    state: 'on'
  action:
  - service: script.security_lighting_on
  mode: single
- id: '1630506102319'
  alias: Renew Let's Encrypt Certificate
  description: ''
  use_blueprint:
    path: mtl010957/renew_certificate_restart_nginx.yaml
    input:
      cert_expiry_sensor: sensor.cert_expiry_timestamp_ha_mtl_desert_dyndns_remote_com
      time_to_check_cert: '3:20:00'
