
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Required http setup for reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24  # Add the IP address of the proxy server
    
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
recorder: !include recorder.yaml
sensor: !include_dir_merge_list sensor

# Nest Stuff
nest: !include nest.yaml

# Remote HA
remote_homeassistant:
  instances: