
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Router
asuswrt: !include asuswrt.yaml

# Nest Stuff
nest: !include nest.yaml

recorder: !include recorder.yaml
sensor: !include_dir_merge_list sensor

